import type { Metadata } from 'next';
import './globals.css';
import PetProvider from 'src/shared/context/pet/pet-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PetProvider>{children}</PetProvider>
      </body>
    </html>
  );
}
