import type { Metadata } from 'next';
import './globals.css';
import PetProvider from 'src/shared/context/pet/pet-provider';
import { RoomProvider } from 'src/liveblocks.config';
import { LiveList, LiveMap, LiveObject } from '@liveblocks/client';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RoomProvider
        id="112345456841"
        initialPresence={{
          pet: {
            position: {},
          },
        }}
        initialStorage={{
          layerIds: new LiveList([]),
          layers: new LiveMap<string, LiveObject<any>>(),
        }}
      >
        <PetProvider>
          <body>{children}</body>
        </PetProvider>
      </RoomProvider>
    </html>
  );
}
